##
## Options for board efm32gg332f1024_wandstem
## Included by the board's makefile
##

## Select linker scripts
LINKER_SCRIPT := ldscripts/miosix-flash-ram.ld
BOARD_LINKER_SCRIPT := unikernel.ld
#BOARD_LINKER_SCRIPT := processes.ld
