#ifndef _APP_ELF_TESTS_
#define _APP_ELF_TESTS_
#include "aelf1.h"
#include "aelf2.h"
#include "aelf3.h"
#include "aelf4.h"
#include "aelf5.h"
#include "aelf6.h"
#include "aelf7.h"
#endif //_APP_ELF_TESTS_
