#ifndef _APP_ELF_TESTS_
#define _APP_ELF_TESTS_
#include "miosix/testsuite/elf_testsuite/aelf1.h"
#include "miosix/testsuite/elf_testsuite/aelf2.h"
#include "miosix/testsuite/elf_testsuite/aelf3.h"
#include "miosix/testsuite/elf_testsuite/aelf4.h"
#include "miosix/testsuite/elf_testsuite/aelf5.h"
#include "miosix/testsuite/elf_testsuite/aelf6.h"
#include "miosix/testsuite/elf_testsuite/aelf7.h"
#endif //_APP_ELF_TESTS_
