##
## Options for board stm32u535cb_rrc
## Included by the board's makefile
##

## Select linker script
LINKER_SCRIPT_PATH := arch/board/stm32u535cb_rrc/
LINKER_SCRIPT := $(LINKER_SCRIPT_PATH)/stm32_128k+256k_rom.ld
