#!/usr/bin/env bash

# After running install-script.sh, this script will clean up temporary files.
# It will not remove the files created by the download.sh script, so that
# running install-script.sh is possible without re-downloading them.

rm -rf binutils-2.44 gcc-14.2.0 gdb-16.2 gdb-obj newlib-3.1.0 newlib-obj \
	gmp-6.3.0 mpfr-4.2.1 mpc-1.3.1 make-4.2.1 expat-2.2.10 ncurses-6.1 \
	makeself-2.4.5 lib quickfix lpc21isp.c

rm -rf objdir/ log/
if [[ $? -ne 0 ]]; then
	sudo rm -rf objdir/ log/
fi

# Installer scripts generated by the build scripts on macOS
rm -rf installers/macos/Scripts
