/***************************************************************************
 *   Copyright (C) 2010-2025 by Terraneo Federico                          *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   As a special exception, if other files instantiate templates or use   *
 *   macros or inline functions from this file, or you compile this file   *
 *   and link it with other works to produce a work based on this file,    *
 *   this file does not by itself cause the resulting work to be covered   *
 *   by the GNU General Public License. However the source code for this   *
 *   file must still be made available in accordance with the GNU General  *
 *   Public License. This exception does not invalidate any other reasons  *
 *   why a work based on this file might be covered by the GNU General     *
 *   Public License.                                                       *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, see <http://www.gnu.org/licenses/>   *
 ***************************************************************************/

#pragma once

namespace miosix {

/**
 * \enum Error
 * This enum is passed as argument to the error handler
 */
enum class Error
{
    /// Unexpected error occurred
    UNEXPECTED,

    /// The heap is full, malloc/new returned NULL
    OUT_OF_MEMORY,

    /// The stack of a thread overflowed
    STACK_OVERFLOW,

    /// A mutex related error such as a deadlock or unlock while not being the
    /// owner happened
    MUTEX_ERROR,

    /// Interrupts are wrongly enabled during the early boot stage
    INTERRUPTS_ENABLED_AT_BOOT,

    /// PauseKernel is wrongly released during the early boot stage
    KERNEL_ALREADY_STARTED_AT_BOOT,

    /// Attempting to register an already registered interrupt or unregistering
    /// the wrong interrupt
    INTERRUPT_REGISTRATION_ERROR,
};

/**
 * Handles unrecoverable errors generated by kernel and causes a reboot.
 * Prints an error message on the Console (only if WITH_ERRLOG is defined
 * in miosix_config.h).
 * Can be called with the kernel not started, started, paused, with interrupts
 * disabled and within an interrupt routine.
 */
[[noreturn]] void errorHandler(Error e);

} //namespace miosix
