##
## Options for board stm32f401re_nucleo
## Included by the board's makefile
##

LINKER_SCRIPT := ldscripts/miosix-flash-ram.ld
BOARD_LINKER_SCRIPT := unikernel.ld
#BOARD_LINKER_SCRIPT := processes.ld
