#!/usr/bin/env bash

# After running install-script.sh, this script will clean up temporary files.
# It will not remove the files created by the download.sh script, so that
# running install-script.sh is possible without re-downloading them.

# Source code
rm -rf binutils-2.45 gcc-15.2.0 gdb-16.3 newlib-4.6.0.20260123 gmp-6.3.0 \
  mpfr-4.2.2 mpc-1.3.1 make-4.4.1 expat-2.7.3 ncurses-6.5 makeself-2.6.0
  
# Build directories
rm -rf binutils_build gdb_build newlib_build
rm -rf gcc_build log
if [[ $? -ne 0 ]]; then
	sudo rm -rf gcc_build log
fi

# Temporary install locations
rm -rf lib dist

# Installer scripts generated by the build scripts on macOS
rm -rf installers/macos/Scripts
