#ifndef _APP_MPU_TESTS_2_
#define _APP_MPU_TESTS_2_
#include "mpu_testsuite/altered_elfs/aelf1.h"
#include "mpu_testsuite/altered_elfs/aelf2.h"
#include "mpu_testsuite/altered_elfs/aelf3.h"
#include "mpu_testsuite/altered_elfs/aelf4.h"
#include "mpu_testsuite/altered_elfs/aelf5.h"
#include "mpu_testsuite/altered_elfs/aelf6.h"
#include "mpu_testsuite/altered_elfs/aelf7.h"
#endif //_APP_MPU_TESTS_2_
